# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='dims',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
