# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171027_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='pieces',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
