# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171027_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='pieces',
        ),
        migrations.AddField(
            model_name='cargo',
            name='type',
            field=models.CharField(default='CUBOID', max_length=255),
        ),
    ]
