# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171027_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='pieces',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
